BMI/Controllers/SAP_POController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BMI.Data;
using Microsoft.EntityFrameworkCore;
using BMI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using ExcelDataReader;
using System.Data;

namespace BMI.Controllers
{
    public class SAP_POController : Controller
    {
        private readonly ApplicationDbContext _db;
        private IWebHostEnvironment Environment;
        private IConfiguration Configuration;

        public SAP_POController(ApplicationDbContext db, IWebHostEnvironment _environment, IConfiguration _configuration)
        {
            _db = db;
            Environment = _environment;
            Configuration = _configuration;
        }

        public async Task<IActionResult> Index(string status, string plant)
        {
            var obj = _db.SAP_PO.Include(a => a.VendorModel).Where(a => a.status == status && a.plant == plant).ToList();
            if (status == "Plant")
            {
                ViewBag.status = "Plant";
            }
            else if (status == "Otw")
            {
                ViewBag.status = "On The Water";
            }
            else
            {
                ViewBag.status = "Closed";
            }
            ViewBag.plant = plant;
            
            return await Task.Run(() => View(obj));
        }

        public async Task<IActionResult> Detail(string refference, string status)
        {
            var obj = _db.SAP_PO_Detail
                .Where(a => a.refference == refference)
                .Select(a => new SAP_PODetailModel
                {
                    id = a.id,
                    sap_code = a.sap_code,
                    Masterdatamodel = a.Masterdatamodel,
                    style = a.style,
                    vessel = a.vessel,
                    unit_price = a.unit_price,
                    qty_pl = a.qty_pl,
                    amount_pl = Math.Round(Convert.ToDouble(a.unit_price * a.qty_pl), 2),
                    qty_received = a.qty_received,
                    amount_received = Math.Round(Convert.ToDouble(a.unit_price * a.qty_received), 2),
                }).ToList();
            ViewBag.qty_pl = obj.Sum(a => a.qty_pl);
            ViewBag.amount_pl = obj.Sum(a => a.amount_pl);
            ViewBag.qty_received = obj.Sum(a => a.qty_received);
            ViewBag.amount_received = obj.Sum(a => a.amount_received);
            ViewBag.refference = refference;
            ViewBag.status = status;
            return await Task.Run(() => View(obj));
        }


        [HttpPost]
        [AutoValidateAntiforgeryToken]
        [Authorize(Roles = "PF,Admin")]
        public async Task<IActionResult> Import(IFormFile postedFile, string plant)
        {
            if (postedFile != null)
            {
                var allowedExtensions = new[] { ".xls", ".xlsx" };
                string fileName = Path.GetFileName(postedFile.FileName);
                var checkextension = Path.GetExtension(fileName).ToLower();

                if (allowedExtensions.Contains(checkextension))
                {
                    List<SAP_PODetailModel> rm_detail = new List<SAP_PODetailModel>();
                    List<SAP_POModel> rm = new List<SAP_POModel>();
                    string path = Path.Combine(this.Environment.WebRootPath, "Uploads");

                    string filePath = Path.Combine(path, fileName);
                    using (FileStream stream = new FileStream(filePath, FileMode.Create))
                    {
                        postedFile.CopyTo(stream);
                    }
                    // For .net core, the next line requires the NuGet package, 
                    //System.Text.Encoding.CodePages
                    System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);

                    using (var stream = System.IO.File.Open(filePath, FileMode.Open, FileAccess.Read))
                    {
                        {
                            IExcelDataReader excelDataReader = ExcelDataReader.ExcelReaderFactory.CreateReader(stream);
                            if (excelDataReader.FieldCount == 21)
                            {

                                var conf = new ExcelDataSetConfiguration()
                                {
                                    ConfigureDataTable = a => new ExcelDataTableConfiguration
                                    {
                                        UseHeaderRow = true
                                    }
                                };

                                DataSet dataSet = excelDataReader.AsDataSet(conf);
                                DataRowCollection row = dataSet.Tables["RM"].Rows;
                                List<object> rowDataList = null;

                                foreach (DataRow item in row)
                                {
                                    rowDataList = item.ItemArray.ToList();
                                    var refference = Convert.ToString(rowDataList[0]);
                                    var unique = _db.SAP_PO.FirstOrDefault(m => m.refference == refference);
                                    if (unique == null)
                                    {
                                        var obj = new SAP_POModel
                                        {
                                            plant = plant,
                                            refference = Convert.ToString(rowDataList[0]),
                                            vendor = Convert.ToString(rowDataList[1]),
                                            sap_po = Convert.ToString(rowDataList[3]),
                                            //pgi = Convert.ToString(rowDataList[4]),
                                            //pgr = Convert.ToString(rowDataList[5]),
                                            //return_no = Convert.ToString(rowDataList[6]),
                                            //delivery_date = Convert.ToDateTime(rowDataList[11]),
                                            etd = Convert.ToDateTime(rowDataList[12]),
                                            eta = Convert.ToDateTime(rowDataList[13]),
                                            invoice = Convert.ToString(rowDataList[14]),
                                            container = Convert.ToString(rowDataList[15]),
                                            bl_no = Convert.ToString(rowDataList[16]),
                                            shipping_line = Convert.ToString(rowDataList[17]),
                                            loading_port = Convert.ToString(rowDataList[18]),
                                            destination = Convert.ToString(rowDataList[19]),
                                            //pgr_date = Convert.ToDateTime(rowDataList[20]),
                                            status = "Otw"
                                        };
                                        _db.SAP_PO.Add(obj);
                                        _db.SaveChanges();
                                    }
                                }


                                foreach (DataRow item in row)
                                {
                                    rowDataList = item.ItemArray.ToList();
                                    rm_detail.Add(new SAP_PODetailModel
                                    {
                                        refference = Convert.ToString(rowDataList[0]),
                                        style = Convert.ToString(rowDataList[2]),
                                        sap_code = Convert.ToString(rowDataList[7]),
                                        unit_price = Convert.ToSingle(rowDataList[8]),
                                        qty_pl = Convert.ToSingle(rowDataList[9]),
                                        vessel = Convert.ToString(rowDataList[10]),
                                    }); ;
                                }
                                _db.SAP_PO_Detail.AddRange(rm_detail);
                                _db.SaveChanges();
                                stream.Close();
                                System.IO.File.Delete(filePath);
                                TempData["msg"] = "File Succesfully Uploaded";
                                TempData["result"] = "success";
                                return await Task.Run(() => Redirect(Request.Headers["Referer"].ToString()));
                            }
                            stream.Close();
                            System.IO.File.Delete(filePath);
                            TempData["msg"] = "Field Column not Match";
                            TempData["result"] = "failed";
                            return await Task.Run(() => Redirect(Request.Headers["Referer"].ToString()));
                        }
                    }
                }
                //jika tidak sesuai extension
                TempData["msg"] = "File Extension must excel file format 'xlsx or xls'";
                TempData["result"] = "failed";
                return await Task.Run(() => Redirect(Request.Headers["Referer"].ToString()));
            }
            TempData["msg"] = "File Empty";
            TempData["result"] = "failed";
            return await Task.Run(() => Redirect(Request.Headers["Referer"].ToString()));
        }

        public async Task<IActionResult> GetData(string refference)
        {
            var obj = _db.SAP_PO.Find(refference);
            return await Task.Run(() => Json(obj));
        }

        public async Task<IActionResult> Delete(string refference)
        {
            var obj = _db.SAP_PO.Find(refference);
            if (obj == null)
            {

BMI/Views/SAP_PO/Detail.cshtml
@model IEnumerable<BMI.Models.SAP_PODetailModel>
@{string refference = ViewBag.refference; }
@{string status = ViewBag.status; }
@{
    ViewData["Title"] = refference;
}
<div class="content-wrapper">
    <section class="content-header">
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-12">

                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Detail List of @refference - @status</h3>
                    </div>

                    <div class="card-body">
                        <table class="table table-bordered table-striped table-sm">
                            <thead>
                                <tr>
                                    <th style="width: 5%;font-size:small">
                                        Code
                                    </th>
                                    <th style="width: 10%;font-size:small">
                                        Description
                                    </th>
                                    <th style="width: 2%;font-size:small">
                                        Style
                                    </th>
                                    <th style="width: 6%;font-size:small">
                                        Vessel
                                    </th>
                                    <th style="width: 3%;font-size:small">
                                        Price
                                    </th>
                                    <th style="width: 3%;font-size:small">
                                        Kg PL
                                    </th>
                                    <th style="width: 3%;font-size:small">
                                        $ PL
                                    </th>
                                    @if (status == "Plant" || status == "Closed")
                                    {
                                        <th style="width: 4%;font-size:small">
                                            Kg Received
                                        </th>
                                        <th style="width: 4%;font-size:small">
                                            $ Received
                                        </th>
                                    }
                                    <th style="width: 3%;font-size:small">
                                        Actions
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var obj in Model)
                                {
                                <tr>
                                    <td style="font-size:small">@obj.sap_code</td>
                                    <td style="font-size:small">@obj.Masterdatamodel.description</td>
                                    <td style="font-size:small">@obj.style</td>
                                    <td style="font-size:small">@obj.vessel</td>
                                    <td style="font-size:small">@Convert.ToDecimal(obj.unit_price).ToString("C")</td>
                                    <td style="font-size:small">@obj.qty_pl</td>
                                    <td style="font-size:small">@Convert.ToDecimal(obj.amount_pl).ToString("C")</td>
                                    @if (status == "Plant" || status == "Closed")
                                    {
                                        <td style="font-size:small">@obj.qty_received</td>
                                        <td style="font-size:small">@Convert.ToDecimal(obj.amount_received).ToString("C")</td>
                                    }
                                    <td>
                                        <form asp-controller="Rm" asp-action="DeleteItemRMPlant" asp-route-id="@obj.id" asp-route-raw_source="@obj.refference" method="post" class="d-inline">
                                            <a href="#" class="btn btn-xs btn-warning change-item-detail-plant"
                                               data-toggle="modal" data-target="#modal-default" data-id="@obj.id">
                                                <i class="fa fa-edit" style="color:ghostwhite;outline:thin"></i>
                                            </a>
                                            <button type="submit" onclick="return confirm ('Delete Item @obj.sap_code' );" class="btn btn-xs btn-danger">
                                                <i class="fa fa-trash"></i>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                                }
                            </tbody>
                            <tfoot>
                                <tr>
                                    @if (status == "Plant" || status == "Closed")
                                    {
                                        <th style="width: 2%;font-size:small" colspan="5">Total</th>
                                        <th style="width: 2%;font-size:small">@(ViewBag.qty_pl)</th>
                                        <th style="width: 2%;font-size:small">@Convert.ToDecimal(ViewBag.amount_pl).ToString("C")</th>
                                        <th style="width: 2%;font-size:small">@(ViewBag.qty_received)</th>
                                        <th style="width: 2%;font-size:small">@Convert.ToDecimal(ViewBag.amount_received).ToString("C")</th>
                                        <th style="width: 2%;font-size:small"></th>
                                    }
                                    else
                                    {
                                        <th style="width: 2%;font-size:small" colspan="5">Total</th>
                                        <th style="width: 2%;font-size:small">@(ViewBag.qty_pl)</th>
                                        <th style="width: 2%;font-size:small">@(Convert.ToDecimal(ViewBag.amount_pl).ToString("C"))</th>
                                        <th></th>
                                    }
                                </tr>
                            </tfoot>
                        </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->
</div>



<div class="modal fade" id="modal-default">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="formModalLabel">Add New Item</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="POST" asp-controller="SAP_PO" asp-action="UpdateDetail" class="form-horizontal">
                    <div class="card-body">
                        <input type="hidden" asp-for="First().id">
                        <div class="form-group row">
                            <label class="col-sm-3  col-form-label"> Hers Code</label>
                            <div class="col-sm-9">
                                <input type="text" placeholder="Item Code" class="form-control" asp-for="First().sap_code">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label">Style</label>
                            <div class="col-sm-9">
                                <input type="text" step="any" placeholder="USD Price" class="form-control" asp-for="First().style">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label">Vessel</label>
                            <div class="col-sm-9">
                                <input type="text" step="any" class="form-control" placeholder="IDR Rate" asp-for="First().vessel">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label">Unit Price</label>
                            <div class="col-sm-9">
                                <input type="text" placeholder="Landing Site" class="form-control" asp-for="First().unit_price">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label">Qty PL</label>
                            <div class="col-sm-9">
                                <input type="number" step="any" class="form-control" placeholder="Packing List" asp-for="First().qty_pl">
                            </div>
                        </div>
                        @if (status == "Plant" || status == "Closed")
                        {
                            <hr />
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Qty Received</label>
                                <div class="col-sm-9">
                                    <input type="number" step="any" class="form-control" placeholder="Qty Received" asp-for="First().qty_received">
                                </div>
                            </div>
                        }

                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Update</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
     /.modal-content 
</div>

<div class="modal fade" id="modal-destroy">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="formModalLabel">Destroy Material</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="POST" asp-controller="Rm" asp-action="Adddestroy" class="form-horizontal">
                    <div class="card-body">
                        <input type="hidden" asp-for="First().sap_code">
                        <input type="hidden" asp-for="First().refference">
                        <input type="hidden" id="status" name="status" value="destroy">
                        <div class="form-group">
                            <label>Qty</label>
                            <div>
                                <input type="number" step="any" placeholder="Qty" class="form-control" asp-for="First().qty_received">
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Reason</label>
                            <div>
                                <input type="text" step="any" placeholder="Please Input Reason" class="form-control" asp-for="First().qty_received">
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Destroy</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
     /.modal-content 
</div>