BMI/Controllers/MasterDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BMI.Data;
using BMI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace BMI.Controllers
{   
    [Authorize(Roles ="Admin")]
    public class MasterDataController : Controller
    {
        private readonly ApplicationDbContext _db;

        public MasterDataController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index()
        {
            var obj = _db.Master_data.OrderBy(a => a.created_at).ToList();
            return await Task.Run(() => View(obj));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Create")]
        public async Task<IActionResult> Create(Masterdatamodel masterdatamodel)
        {
            if (ModelState.IsValid)
            {
                //var obj = new Masterdatamodel
                //{
                //    sap_code = masterdatamodel.sap_code,
                //    hers_code = masterdatamodel.hers_code,
                //    description = masterdatamodel.description,
                //    lbs = masterdatamodel.lbs,
                //    category = masterdatamodel.category,
                //    created_at = DateTime.Now
                //};
                //_db.Master_data.Add(obj);
                _db.Master_data.Add(masterdatamodel);
                _db.SaveChanges();
                TempData["msg"] = "Item Succesfully Added";
                TempData["result"] = "success";
                return await Task.Run(() => RedirectToAction("Index"));
            }
            TempData["msg"] = "Item Failed to Add";
            TempData["result"] = "failed";
            return await Task.Run(() => RedirectToAction("Index"));

        }

        public JsonResult Getmasterbmi(string id)
        {
            var obj = _db.Master_data.Find(id);
            return Json(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Update")]
        public async Task<IActionResult> Update(Masterdatamodel masterdatamodel)
        {
            if (ModelState.IsValid)
            {
                _db.Master_data.Update(masterdatamodel);


                //var obj = _db.Master_data.Find(masterdatamodel.sap_code);

                //obj.description = masterdatamodel.description;
                //obj.lbs = masterdatamodel.lbs;
                //obj.category = masterdatamodel.category;
                //obj.updated_at = DateTime.Now;

                //_db.Entry(obj).State = EntityState.Modified;
                _db.SaveChanges();

                TempData["msg"] = "Item Succesfully Updated";
                TempData["result"] = "success";
                return await Task.Run(() => RedirectToAction("Index"));
            }
            TempData["msg"] = "Item Failed Added";
            TempData["result"] = "failed";
            return await Task.Run(() => RedirectToAction("Index"));
        }

        [Authorize(Policy = "Delete")]
        public async Task<IActionResult> Delete(string id)
        {
            var obj = _db.Master_data.Find(id);
            _db.Master_data.Remove(obj);
            _db.SaveChanges();
            TempData["msg"] = "Item Succesfully Deleted";
            TempData["result"] = "success";
            return await Task.Run(() => RedirectToAction("Index"));
        }

    }
}

BMI/Views/MasterData/Index.cshtml
@model IEnumerable<BMI.Models.Masterdatamodel>
@{
    ViewData["Title"] = "Master BMI";
}
<div class="content-wrapper">
    <section class="content-header">
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-12">

                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">BMI Master List</h3>
                        <div class="card-tools ">
                            <button class="btn btn-sm float-right mx-1 add-master-data"
                                    data-toggle="modal" data-target="#modal-default">
                                <i class="fa fa-plus">
                                </i>
                            </button>
                        </div>
                    </div>

                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped table-sm">
                            <thead>
                                <tr>
                                    <th style="width: 7%;font-size:small">
                                        SAP Code
                                    </th>
                                    <th style="width: 15%;font-size:small">
                                        Description
                                    </th>
                                    <th style="width: 5%;font-size:small">
                                        # Code
                                    </th>
                                    <th style="width: 3%;font-size:small">
                                        Lbs
                                    </th>
                                    <th style="width: 5%;font-size:small">
                                        3770 PF
                                    </th>
                                    <th style="width: 5%;font-size:small">
                                        3710 PF
                                    </th>
                                    <th style="width: 5%;font-size:small">
                                        Std Price
                                    </th>
                                    <th style="width: 8%;font-size:small">
                                        Category
                                    </th>
                                    <th style="width: 3%;font-size:small">
                                        Action
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var obj in Model)
                                {
                                <tr>
                                    <td style="font-size:small">@obj.sap_code</td>
                                    <td style="font-size:small">@obj.description</td>
                                    <td style="font-size:small">@obj.hers_code</td>
                                    <td style="font-size:small">@obj.lbs</td>
                                    <td style="font-size:small">@obj.PF3770</td>
                                    <td style="font-size:small">@obj.PF3710</td>
                                    <td style="font-size:small">@obj.standard_price</td>
                                    <td style="font-size:small">@obj.category</td>
                                    <td>
                                        <form asp-controller="MasterData" asp-route-id="@obj.sap_code" asp-action="Delete" method="post">
                                            <a data-toggle="modal" data-target="#modal-default" data-id="@obj.sap_code" class="btn btn-xs btn-warning update-master-data">
                                                <i class="fa fa-edit" style="color:whitesmoke;outline:thin">
                                                </i>
                                            </a>
                                            <button type="submit" onclick="return confirm ('Delete Item @obj.sap_code');" class="btn btn-xs btn-danger">
                                                <i class="fa fa-trash">
                                                </i>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>


<div class="modal fade" id="modal-default">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="formModalLabel">Add Item</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body mb-2">
                <form method="POST" asp-action="Create">
                    <div class="card-body">
                        <div class="form-group sap-code">
                            <label>SAP Code</label>
                            <input type="text" step="any" class="form-control" asp-for="First().sap_code"
                                   placeholder="SAP Code">
                            <span asp-validation-for="First().sap_code" class="text-danger" style="font-size:smaller"> </span>
                        </div>
                        <div class="form-group">
                            <label>Description</label>
                            <input type="text" class="form-control" asp-for="First().description"
                                   placeholder="Description">
                            <span asp-validation-for="First().description" class="text-danger" style="font-size:smaller"> </span>
                        </div>
                        <div class="form-group">
                            <label>HERS Code</label>
                            <input type="number" step="any" class="form-control" asp-for="First().hers_code"
                                   placeholder="Hers Code">
                            <span asp-validation-for="First().hers_code" class="text-danger" style="font-size:smaller"> </span>
                        </div>
                        <div class="form-group">
                            <label>Lbs</label>
                            <input type="number" step="any" class="form-control" asp-for="First().lbs"
                                   placeholder="Lbs">
                            <span asp-validation-for="First().lbs" class="text-danger" style="font-size:smaller"> </span>
                        </div>
                        <div class="form-group">
                            <label>3770 Processing Fee/Lb</label>
                            <input type="number" step="any" class="form-control" asp-for="First().PF3770"
                                   placeholder="Processing Fee 3770">
                            <span asp-validation-for="First().PF3770" class="text-danger" style="font-size:smaller"> </span>
                        </div>
                        <div class="form-group">
                            <label>3710 Processing Fee/Lb</label>
                            <input type="number" step="any" class="form-control" asp-for="First().PF3710"
                                   placeholder="Processing Fee 3710">
                            <span asp-validation-for="First().PF3710" class="text-danger" style="font-size:smaller"> </span>
                        </div>
                        <div class="form-group">
                            <label>Standard Price/Lb</label>
                            <input type="number" step="any" class="form-control" asp-for="First().standard_price"
                                   placeholder="Standard Price">
                            <span asp-validation-for="First().standard_price" class="text-danger" style="font-size:smaller"> </span>
                        </div>
                        <div class="form-group">
                            <label>Category</label>
                            <select class="form-control" asp-for="First().category">
                                <option>Saku</option>
                                <option>Loin</option>
                                <option>10, 8, 6 Oz Steaks</option>
                                <option>4 Oz Steak</option>
                                <option>Poke & By Products</option>
                                <option>Raw Material</option>
                            </select>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="submit" value="Create" class="btn btn-primary">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- /.modal-content -->
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}